"""Build news_calendar.json for the Tape Reader's Strategy panel "custom" strategy
(day-of-week / time-of-day / news-anchored entries). Consumes Phase 0's reconciliation
(phase0_reconcile.py) plus the manual verification of its 31 DISAGREE rows against
official sources (BLS, ADP, ISM, Conference Board, UMich, the Fed's historical FOMC
convention), documented in the reconciliation report:
https://claude.ai/artifact/7fgamHexC3WBjv8mNWDx6i

Output is per-occurrence, not per-category (see the plan,
C:\\Users\\ruben\\.claude\\plans\\tender-gliding-bunny.md): a category's "typical" time
is display metadata only, never what an actual entry anchors on.

Run once; output is checked in like lh5_pack.json/rf2_pack.json, not regenerated by
build_viewer3.py itself.

From 2025-04-05 (the day after the Phase 0 Forex Factory file ends) Forex Factory comes
from newfac's nightly full-history CSV instead, downloaded fresh on every run -- see
extend_with_newfac(). `python build_news_calendar.py --extend-only` redoes just that step
on the checked-in news_calendar.json, for a machine without the Phase 0 source files.
"""
import datetime
import hashlib
import json
import os
import re
import sys
import urllib.request

import pandas as pd

import phase0_reconcile as P0

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------- manual verification
# The 31 DISAGREE rows, checked against official sources (see the report). Keyed by
# (date, ff_event) -> etMinute. 11 rows verified against a fixed official schedule
# (BLS 8:30/10:00, ADP 8:15, ISM/Conference Board/UMich 10:00); 13 FOMC-family rows
# resolved because both independent sources land within minutes of the same round
# historical FOMC time (12:30 or 14:15 ET pre-2019 depending on whether that meeting
# had a press conference, 14:00 ET from 2019 on); Not present here = still unresolved
# (7 speech rows -- no official fixed schedule to check a speech against, and the large
# gaps look like two different events under one label, not a timing error).
DISAGREE_VERIFIED = {
    ('2011-06-28', 'CB Consumer Confidence'): 10 * 60,
    ('2014-03-05', 'ISM Services PMI'): 10 * 60,
    ('2015-08-03', 'ISM Manufacturing PMI'): 10 * 60,
    ('2016-01-15', 'Prelim UoM Consumer Sentiment'): 10 * 60,
    ('2016-02-12', 'Prelim UoM Consumer Sentiment'): 10 * 60,
    ('2020-04-29', 'Advance GDP q/q'): 8 * 60 + 30,
    ('2021-03-10', 'CPI y/y'): 8 * 60 + 30,
    ('2021-05-14', 'Core Retail Sales m/m'): 8 * 60 + 30,
    ('2022-03-02', 'ADP Non-Farm Employment Change'): 8 * 60 + 15,
    ('2022-03-10', 'CPI y/y'): 8 * 60 + 30,
    ('2023-06-29', 'Unemployment Claims'): 8 * 60 + 30,
    # FOMC family: round time both sources land within minutes of
    ('2011-04-27', 'Federal Funds Rate'): 12 * 60 + 30,
    ('2011-06-22', 'Federal Funds Rate'): 12 * 60 + 30,
    ('2011-08-09', 'Federal Funds Rate'): 14 * 60 + 15,
    ('2011-09-21', 'FOMC Statement'): 14 * 60 + 15,
    ('2011-11-02', 'FOMC Statement'): 12 * 60 + 30,
    ('2011-11-22', 'FOMC Meeting Minutes'): 14 * 60,
    ('2011-12-13', 'FOMC Statement'): 14 * 60 + 15,
    ('2012-01-03', 'FOMC Meeting Minutes'): 14 * 60,
    ('2012-01-25', 'FOMC Statement'): 12 * 60 + 30,
    ('2012-06-20', 'FOMC Statement'): 12 * 60 + 30,
    ('2012-08-01', 'FOMC Statement'): 14 * 60 + 15,
    ('2015-08-19', 'FOMC Meeting Minutes'): 14 * 60,
    ('2020-01-03', 'FOMC Meeting Minutes'): 14 * 60,
}

# ---------------------------------------------------------------- OFFICIAL_STANDARD
# Never auto-shipped without an explicit per-category go-ahead (the plan's own rule).
# Approved 2026-09-21: categories with a genuinely fixed, single-time-of-day government
# or industry-published schedule, applied only to their DAY_ONLY occurrences (an
# occurrence that already has a real observed/cross-verified/verified time keeps it --
# this never overrides real data, only fills a gap neither source had anything for).
# Deliberately EXCLUDES the whole FOMC family (Federal Funds Rate, FOMC Statement,
# FOMC Meeting Minutes, FOMC Press Conference, FOMC Economic Projections) -- the
# historical DISAGREE resolution above proves the release time genuinely varies by
# era (12:30 / 14:00 / 14:15 ET), so a single blanket time would be actively wrong for
# some of the very occurrences it would apply to; those stay DAY_ONLY if unresolved.
OFFICIAL_STANDARD = {
    # BLS, confirmed 8:30 AM ET (bls.gov)
    'CPI y/y': (8 * 60 + 30, 'BLS standard schedule, bls.gov'),
    'CPI m/m': (8 * 60 + 30, 'BLS standard schedule, bls.gov'),
    'Core CPI m/m': (8 * 60 + 30, 'BLS standard schedule, bls.gov (same report as CPI)'),
    'PPI m/m': (8 * 60 + 30, 'BLS standard schedule, bls.gov'),
    'Core PPI m/m': (8 * 60 + 30, 'BLS standard schedule, bls.gov (same report as PPI)'),
    'Unemployment Rate': (8 * 60 + 30, 'BLS Employment Situation, bls.gov'),
    'Non-Farm Employment Change': (8 * 60 + 30, 'BLS Employment Situation, bls.gov'),
    'Average Hourly Earnings m/m': (8 * 60 + 30, 'BLS Employment Situation, bls.gov (same report)'),
    'JOLTS Job Openings': (10 * 60, 'BLS standard schedule, bls.gov'),
    # DOL, well-established weekly 8:30 AM ET
    'Unemployment Claims': (8 * 60 + 30, 'Dept. of Labor weekly release, well-established 8:30 ET'),
    # Census Bureau, well-established 8:30 AM ET
    'Retail Sales m/m': (8 * 60 + 30, 'Census Bureau standard schedule'),
    'Core Retail Sales m/m': (8 * 60 + 30, 'Census Bureau standard schedule (same report)'),
    # BEA, well-established 8:30 AM ET
    'Advance GDP q/q': (8 * 60 + 30, 'BEA standard schedule'),
    'Prelim GDP q/q': (8 * 60 + 30, 'BEA standard schedule (same report family)'),
    'Final GDP q/q': (8 * 60 + 30, 'BEA standard schedule (same report family)'),
    'Core PCE Price Index m/m': (8 * 60 + 30, 'BEA standard schedule'),
    # ADP, well-established 8:15 AM ET
    'ADP Non-Farm Employment Change': (8 * 60 + 15, 'ADP Research Institute standard schedule'),
    # ISM, well-established 10:00 AM ET
    'ISM Manufacturing PMI': (10 * 60, 'ISM standard schedule'),
    'ISM Services PMI': (10 * 60, 'ISM standard schedule'),
    # Conference Board, well-established 10:00 AM ET
    'CB Consumer Confidence': (10 * 60, 'Conference Board standard schedule'),
    # University of Michigan, well-established 10:00 AM ET
    'Prelim UoM Consumer Sentiment': (10 * 60, 'University of Michigan standard schedule'),
    'Revised UoM Consumer Sentiment': (10 * 60, 'University of Michigan standard schedule'),
    # NAR, confirmed 10:00 AM ET (nar.realtor)
    'Pending Home Sales m/m': (10 * 60, 'NAR standard schedule, nar.realtor'),
    # not a government schedule -- derived from this project's own data instead: all
    # 10 of Flash Services PMI's own CROSS_VERIFIED/SINGLE_SOURCE occurrences (2022,
    # 2023, 2025) land on exactly 09:45 ET with zero exceptions, stronger evidence
    # than an external source I couldn't reach
    'Flash Services PMI': (9 * 60 + 45, "this category's own 10/10 observed occurrences, unanimous"),
}

# ---------------------------------------------------------------- priority order
# For "Most important release": a fixed, documented, editable table -- not logic
# buried in the reduction function. Ties among checked, present categories break by
# this order only, deterministically, never by what price did afterward.
NEWS_PRIORITY = [
    'Federal Funds Rate', 'FOMC Statement',            # FOMC decision
    'Non-Farm Employment Change',                        # NFP
    'CPI m/m', 'CPI y/y', 'Core CPI m/m',
    'Core PCE Price Index m/m',
    'FOMC Press Conference', 'FOMC Meeting Minutes',
    'PPI m/m', 'Core PPI m/m',
    'Retail Sales m/m', 'Core Retail Sales m/m',
    'Advance GDP q/q', 'Prelim GDP q/q', 'Final GDP q/q',
    'ISM Manufacturing PMI', 'ISM Services PMI',
    'ADP Non-Farm Employment Change',
    'JOLTS Job Openings',
    'Unemployment Claims',
    'Unemployment Rate', 'Average Hourly Earnings m/m',
    'CB Consumer Confidence', 'Prelim UoM Consumer Sentiment', 'Revised UoM Consumer Sentiment',
    'Housing Starts', 'New Home Sales', 'Pending Home Sales m/m', 'Durable Goods Orders m/m',
    'Fed Chair Powell Speaks', 'Fed Chair Powell Testifies',
    'FOMC Member Bullard Speaks', 'FOMC Member Waller Speaks', 'FOMC Member Williams Speaks',
    'FOMC Economic Projections',
    # everything else: whatever order ALIAS enumerates them in
]


def apply_official_standard(events):
    """Fill each DAY_ONLY occurrence of an OFFICIAL_STANDARD category with that
    category's fixed schedule time, in place. Only DAY_ONLY rows are touched: an
    occurrence with an observed / cross-verified / verified time keeps it, and one whose
    sources conflict (DISAGREE, INVESTING_INTERNAL_CONFLICT, AMBIGUOUS, UNMATCHED) stays
    untradable -- a standard time fills a gap, it never overrides or arbitrates. Plain
    dicts, no pandas, so it can also be run on an already-built news_calendar.json.
    Returns the number of rows filled."""
    n = 0
    for e in events:
        std = OFFICIAL_STANDARD.get(e['eventName'])
        if e['status'] != 'DAY_ONLY' or std is None:
            continue
        e['etMinute'], e['status'], e['standardSource'] = std[0], 'OFFICIAL_STANDARD', std[1]
        n += 1
    return n


def typical_et_minute(events, cid):
    """Display-only 'typical' time: the most common resolved etMinute of the category,
    lowest minute on a tie (what pandas' Series.mode().iloc[0] gives). Never an anchor."""
    counts = {}
    for e in events:
        if e['catId'] == cid and e['etMinute'] is not None:
            counts[e['etMinute']] = counts.get(e['etMinute'], 0) + 1
    if not counts:
        return None
    return int(min(counts, key=lambda m: (-counts[m], m)))


def slugify(name):
    return re.sub(r'_+', '_', re.sub(r'[^a-z0-9]+', '_', name.lower())).strip('_')


# ---------------------------------------------------------------- Forex Factory, 2025-04-05 on
# newfac (github.com/janickfarrell/newfac) re-scrapes Forex Factory's whole calendar every
# night and publishes it at this fixed URL, times in GMT. Checked against the Phase 0 ledger
# before use: same date and time on 92.6% of CROSS_VERIFIED rows and 100% of OFFICIAL_STANDARD
# ones, and it repeats the old file's own odd times (e.g. CPI 07:30 on 2021-03-10), so it is
# the same source, continued -- not a new one.
NEWFAC_URL = ('https://github.com/janickfarrell/newfac/releases/download/'
              'calendar-data/forexfactory_calendar.csv')
NEWFAC_FROM = '2025-04-05'   # the day after the Phase 0 Forex Factory file ends
# Before NEWFAC_FROM newfac only fills gaps: the Phase 0 FF file kept High-impact events only,
# so e.g. medium-rated CPI m/m and jobless-claims releases were missing. A gap is a (date,
# category) with no row at all AND none of that category the day before or after -- an
# evening release the old file dated to the next day is the same release, not a new one.
NEWFAC_HISTORY_FROM = '2007-01-01'
# newfac relabels past events with Forex Factory's current names. Only a pure relabel of the
# same release is mapped back; 'FOMC Member Powell Speaks' (his speeches as governor, chair
# and ex-chair under one name) and 'Fed Chairman Warsh Speaks/Testifies' are left out until
# the user decides what they should count as.
NEWFAC_RENAME = {'Fed Chairman Powell Testifies': 'Fed Chair Powell Testifies'}
NEWFAC_UNTIMED = ('All Day', 'Tentative')   # a real release day with no clock time


def fetch_newfac():
    """Download newfac's CSV (kept in newscal_work/ for the record). Offline, fall back to
    the copy from the last run, and say so in the metadata. Returns (text, meta)."""
    path = os.path.join(P0.WORK, 'newfac_forexfactory_calendar.csv')
    try:
        raw = urllib.request.urlopen(NEWFAC_URL, timeout=120).read()
        os.makedirs(P0.WORK, exist_ok=True)
        with open(path, 'wb') as f:
            f.write(raw)
        when = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%MZ')
    except OSError as err:
        if not os.path.exists(path):
            raise
        print('newfac download failed (%s); using the cached copy' % err)
        with open(path, 'rb') as f:
            raw = f.read()
        when = datetime.datetime.fromtimestamp(os.path.getmtime(path), datetime.timezone.utc) \
            .strftime('%Y-%m-%dT%H:%MZ') + ' (cached)'
    meta = {'source': NEWFAC_URL, 'sha256': hashlib.sha256(raw).hexdigest(), 'downloadedAt': when}
    return raw.decode('utf-8-sig'), meta


def load_newfac(text, date_from, date_to):
    """USD rows whose (relabel-mapped) name is a Phase 0 category, with a New York date in
    [date_from, date_to]. Returns ({(date, name): etMinute or None}, skipped rows).
    A row whose time field names a reference period instead of a clock time ('Oct Data',
    'Sep 27th' -- the 2025 shutdown's catch-up figures, published alongside a real release)
    is not a release of its own and is skipped; a (date, name) with a timed row keeps it."""
    import csv, io
    rows, skipped = {}, []
    lo = (datetime.date.fromisoformat(date_from) - datetime.timedelta(days=1)).isoformat()
    for r in csv.DictReader(io.StringIO(text)):
        name = NEWFAC_RENAME.get(r['event'], r['event'])
        if r['currency'] != 'USD' or name not in P0.ALIAS:
            continue
        day = datetime.datetime.strptime(r['date'], '%a %b %d %Y').date()
        if not lo <= day.isoformat() <= date_to:   # a day of margin: GMT -> NY can go back one
            continue
        if re.fullmatch(r'\d{1,2}:\d{2}', r['time']):
            h, m = map(int, r['time'].split(':'))
            et = (pd.Timestamp(day.year, day.month, day.day, h, m, tz='UTC')
                  .tz_convert('America/New_York'))
            day, etm = et.date(), et.hour * 60 + et.minute
        elif r['time'] in NEWFAC_UNTIMED:
            etm = None
        else:
            skipped.append((day.isoformat(), name, r['time']))
            continue
        key = (day.isoformat(), name)
        if not date_from <= key[0] <= date_to:
            continue
        if key not in rows or (rows[key] is None and etm is not None) or \
                (etm is not None and etm < rows[key]):
            rows[key] = etm   # a timed row beats an untimed one; two timed ones: the earlier
    return rows, skipped


def extend_with_newfac(events, ff_rows, today):
    """Add newfac's rows to `events`, in place, with Phase 0's own status rules.
    From NEWFAC_FROM on, a (date, category) the calendar already has (an Investing.com row
    from 2025-04-05 to 2025-08-15) is reconciled, not duplicated: SINGLE_SOURCE_INVESTING ->
    CROSS_VERIFIED within 1 minute, DISAGREE otherwise; any other status keeps its status.
    Before NEWFAC_FROM, existing rows are never touched: only gaps are added (see
    NEWFAC_HISTORY_FROM). Rows after `today` are the published schedule, marked 'scheduled'.
    The previous state of a reconciled row is kept in 'preNewfac' and every added row carries
    'newfac': True, so strip_newfac() can undo this exactly. Returns a Counter."""
    from collections import Counter
    done = Counter()
    have, old_keys = {}, set()
    for e in events:
        if e['eventName'] == FOMC_CAT_NAME:
            continue
        old_keys.add((e['date'], e['eventName']))
        if e['date'] >= NEWFAC_FROM:
            have.setdefault((e['date'], e['eventName']), []).append(e)
    near = lambda d, n: (datetime.date.fromisoformat(d) + datetime.timedelta(days=n)).isoformat()
    for (date, name), etm in sorted(ff_rows.items()):
        if date < NEWFAC_FROM:
            if (date, name) in old_keys:
                continue
            if (near(date, -1), name) in old_keys or (near(date, 1), name) in old_keys:
                done['history: same release a day off, skipped'] += 1
                continue
        if (date, name) in have:
            for e in have[(date, name)]:
                e['preNewfac'] = {'status': e['status'], 'etMinute': e['etMinute'],
                                  'ff': e['sourceTimes']['ff']}
                e['sourceTimes']['ff'] = etm
                if e['status'] == 'SINGLE_SOURCE_INVESTING' and etm is not None:
                    inv = e['sourceTimes']['investing']
                    if abs(etm - inv) <= 1:
                        e['status'] = 'CROSS_VERIFIED'
                    else:
                        e['status'], e['etMinute'] = 'DISAGREE', None
                done['overlap -> ' + e['status']] += 1
            continue
        if P0.ALIAS[name] is None:
            status, et = 'UNMATCHED', None
        elif name in P0.AMBIGUOUS_FF_CATEGORIES:
            status, et = 'AMBIGUOUS', None
        elif etm is not None:
            status, et = 'SINGLE_SOURCE_FF', etm
        else:
            status, et = 'DAY_ONLY', None
        row = {'date': date, 'catId': slugify(name), 'eventName': name,
               'etMinute': et, 'status': status,
               'sourceTimes': {'ff': etm, 'investing': None}, 'newfac': True}
        if date > today:
            row['scheduled'] = True
        events.append(row)
        done[('history' if date < NEWFAC_FROM else 'scheduled' if date > today else 'new') +
             ' ' + status] += 1
    return done


def strip_newfac(events):
    """Undo extend_with_newfac() (and any OFFICIAL_STANDARD fill of its rows), in place."""
    events[:] = [e for e in events if not e.get('newfac')]
    for e in events:
        pre = e.pop('preNewfac', None)
        if pre:
            e['status'], e['etMinute'], e['sourceTimes']['ff'] = pre['status'], pre['etMinute'], pre['ff']


FOMC_CAT_ID, FOMC_CAT_NAME = 'fomc_decision_day', 'FOMC decision day'


def add_fomc_decision_days(events, days):
    """Append one 'FOMC decision day' row per date in `days`. Where that date has a resolved
    Federal Funds Rate / FOMC Statement time, reuse it (linked, not re-derived) with the status
    of the first such row that day; otherwise DAY_ONLY -- a blanket 14:00 is never asserted.
    (Plain-dict version of the pandas groupby().first() this replaced; same values.)"""
    fomc_resolved, fomc_status, scheduled = {}, {}, set()
    for e in events:
        if e['eventName'] in ('Federal Funds Rate', 'FOMC Statement'):
            fomc_status.setdefault(e['date'], e['status'])
            if e.get('scheduled'):
                scheduled.add(e['date'])
            if e['etMinute'] is not None:
                fomc_resolved.setdefault(e['date'], e['etMinute'])
    for d in sorted(days):
        et = fomc_resolved.get(d)
        status = fomc_status.get(d, 'DAY_ONLY') if et is not None else 'DAY_ONLY'
        row = {'date': d, 'catId': FOMC_CAT_ID, 'eventName': FOMC_CAT_NAME,
               'etMinute': et, 'status': status,
               'sourceTimes': {'ff': None, 'investing': None}}
        if d in scheduled:
            row['scheduled'] = True   # linked to a rate decision that has not happened yet
        events.append(row)


def et_minute(ts):
    if pd.isna(ts):
        return None
    return ts.hour * 60 + ts.minute


def main():
    print('Running Phase 0 reconciliation...')
    result = P0.main()
    rec = result['rec']

    priority_rank = {name: i for i, name in enumerate(NEWS_PRIORITY)}
    all_cats = sorted(P0.ALIAS.keys())
    for name in all_cats:
        if name not in priority_rank:
            priority_rank[name] = len(NEWS_PRIORITY) + all_cats.index(name)

    events = []
    for _, r in rec.iterrows():
        status = r.status
        override = DISAGREE_VERIFIED.get((r.date, r.ff_event))
        if status == 'DISAGREE' and override is not None:
            status = 'OFFICIAL_VERIFIED'
            et = override
        elif status == 'DISAGREE':
            et = None  # unresolved: 7 speech rows, stays non-tradable
        elif status in ('CROSS_VERIFIED', 'SINGLE_SOURCE_INVESTING'):
            et = et_minute(r.inv_et) if pd.notna(r.inv_et) else et_minute(r.ff_et)
        elif status == 'SINGLE_SOURCE_FF':
            et = et_minute(r.ff_et)
        else:  # INVESTING_INTERNAL_CONFLICT, UNMATCHED, AMBIGUOUS, DAY_ONLY
            et = None
        events.append({
            'date': r.date,
            'catId': slugify(r.ff_event),
            'eventName': r.ff_event,
            'etMinute': et,
            'status': status,
            'sourceTimes': {
                'ff': et_minute(r.ff_et) if pd.notna(r.ff_et) else None,
                'investing': et_minute(r.inv_et) if pd.notna(r.inv_et) else None,
            },
        })

    # ---------------- Forex Factory from 2025-04-05 on (newfac, downloaded fresh) ----------------
    text, newfac_meta = fetch_newfac()
    today = datetime.date.today().isoformat()
    ff_rows, skipped = load_newfac(text, NEWFAC_HISTORY_FROM, '9999-12-31')
    print('newfac:', dict(extend_with_newfac(events, ff_rows, today)),
          '-- skipped', len(skipped), 'reference-period rows (e.g. "Oct Data")')
    newfac_meta.update({'from': NEWFAC_FROM, 'historyFrom': NEWFAC_HISTORY_FROM, 'to': today,
                        'scheduledTo': max(d for d, _ in ff_rows)})

    # ---------------- OFFICIAL_STANDARD: fill the approved categories' DAY_ONLY rows ----------------
    # Before the FOMC supplement below, which reads Federal Funds Rate / FOMC Statement times --
    # neither is in OFFICIAL_STANDARD, so the order cannot change what it links to.
    print('OFFICIAL_STANDARD rows filled:', apply_official_standard(events))

    # ---------------- FOMC decision day supplement (rf2_tape.fomc_days(), 2016-2026) ----------------
    # Fills gaps in Forex Factory's own Federal Funds Rate/FOMC Statement coverage (2012-2013,
    # parts of 2020-2021). Where a decision date already has a resolved time from the reconciled
    # Federal Funds Rate/FOMC Statement events, reuse it (linked, not re-derived); a gap date
    # with no such resolution stays DAY_ONLY -- OFFICIAL_STANDARD (e.g. asserting 14:00 ET) is
    # never auto-shipped per the plan, only on your explicit go-ahead.
    import rf2_tape
    add_fomc_decision_days(events, rf2_tape.fomc_days())
    all_cats.append(FOMC_CAT_NAME)
    priority_rank[FOMC_CAT_NAME] = -1  # highest priority: the decision itself

    # categories: name, note (coverage-gap caveats from the FF README), priority rank,
    # display-only typical time (mode of resolved etMinute values -- never an anchor)
    NOTES = {
        'Unemployment Claims': 'Forex Factory\u2019s own source documents this as unreliable for '
            'systematic use \u2014 whole years missing (2007, 2019, 2021, 2022), roughly 33/yr '
            'observed vs. the true weekly ~52.',
        'Durable Goods Orders m/m': 'The underlying Forex Factory source is missing this '
            'category\u2019s data entirely 2021\u20132025.',
        'CB Consumer Confidence': 'Sparse 2020\u20132022 (COVID-era scraper gaps) in the underlying source.',
    }
    events_df = pd.DataFrame(events)
    categories = []
    for name in all_cats:
        cid = slugify(name)
        typical = typical_et_minute(events, cid)
        categories.append({
            'id': cid, 'name': name, 'note': NOTES.get(name),
            'priorityRank': priority_rank[name],
            'typicalEtMinute': typical,
        })

    ff_min, ff_max = result['ff_coverage']
    ff_max = max([ff_max] + [d for d, _ in ff_rows if d <= today])
    inv_min, inv_max = result['investing_coverage']
    cross_min = max(ff_min, inv_min)
    cross_max = min(ff_max, inv_max)

    out = {
        'builtFrom': 'phase0_reconcile.py + manual verification, ' + today +
                     '; newfac Forex Factory ' + newfac_meta['downloadedAt'],
        'ffCoverage': [ff_min, ff_max],
        'investingCoverage': [inv_min, inv_max],
        'crossVerifiedCoverage': [cross_min, cross_max],
        'ffLive': newfac_meta,
        'newsPriority': NEWS_PRIORITY,
        'categories': categories,
        'events': events,
    }
    out_path = os.path.join(HERE, 'news_calendar.json')
    with open(out_path, 'w') as f:
        json.dump(out, f, separators=(',', ':'))
    print('\nWrote', out_path, '--', len(events), 'events,', len(categories), 'categories')
    print('status counts in final events:')
    print(events_df.status.value_counts())
    resolvable = events_df[events_df.etMinute.notna()]
    print('events with a usable etMinute (timing-preset eligible):', len(resolvable))


def extend_only():
    """Redo only the newfac step on the checked-in news_calendar.json: undo the previous
    extension, download newfac again, extend, refill OFFICIAL_STANDARD, relink the FOMC
    decision days. Needs no Phase 0 source files. Refuses to write if any row before
    NEWFAC_FROM would change."""
    path = os.path.join(HERE, 'news_calendar.json')
    with open(path) as f:
        cal = json.load(f)
    events = cal['events']
    # compared by value: the old pandas FOMC step wrote 840.0 where this writes 840 (the
    # page reads both as 840), so a text comparison would flag a non-change
    def canon(e):
        m = e['etMinute']
        return json.dumps(dict(e, etMinute=int(m) if m is not None else None), sort_keys=True)
    before = [canon(e) for e in events if e['date'] < NEWFAC_FROM and not e.get('newfac')]
    strip_newfac(events)
    fomc_days = [e['date'] for e in events if e['eventName'] == FOMC_CAT_NAME]
    events[:] = [e for e in events if e['eventName'] != FOMC_CAT_NAME]
    text, meta = fetch_newfac()
    today = datetime.date.today().isoformat()
    ff_rows, skipped = load_newfac(text, NEWFAC_HISTORY_FROM, '9999-12-31')
    print('newfac:', dict(extend_with_newfac(events, ff_rows, today)),
          '-- skipped', len(skipped), 'reference-period rows (e.g. "Oct Data")')
    print('OFFICIAL_STANDARD rows filled:', apply_official_standard(events))
    add_fomc_decision_days(events, fomc_days)
    after = [canon(e) for e in events if e['date'] < NEWFAC_FROM and not e.get('newfac')]
    assert sorted(before) == sorted(after), 'a row before %s changed; not written' % NEWFAC_FROM
    for c in cal['categories']:
        c['typicalEtMinute'] = typical_et_minute(events, c['id'])
    meta.update({'from': NEWFAC_FROM, 'historyFrom': NEWFAC_HISTORY_FROM, 'to': today,
                 'scheduledTo': max(d for d, _ in ff_rows)})
    cal['ffLive'] = meta
    cal['ffCoverage'][1] = max([cal['ffCoverage'][1]] + [d for d, _ in ff_rows if d <= today])
    cal['crossVerifiedCoverage'] = [max(cal['ffCoverage'][0], cal['investingCoverage'][0]),
                                    min(cal['ffCoverage'][1], cal['investingCoverage'][1])]
    cal['builtFrom'] = cal['builtFrom'].split('; newfac')[0] + '; newfac Forex Factory ' + meta['downloadedAt']
    with open(path, 'w') as f:
        json.dump(cal, f, separators=(',', ':'))
    print('Wrote', path, '--', len(events), 'events; rows before', NEWFAC_FROM, 'unchanged')


if __name__ == '__main__':
    extend_only() if '--extend-only' in sys.argv[1:] else main()
