"""Build news_calendar.json for the Tape Reader's Strategy panel "custom" strategy
(day-of-week / time-of-day / news-anchored entries). Consumes Phase 0's reconciliation
(phase0_reconcile.py) plus the manual verification of its 31 DISAGREE rows against
official sources (BLS, ADP, ISM, Conference Board, UMich, the Fed's historical FOMC
convention), documented in the reconciliation report:
https://claude.ai/artifact/7fgamHexC3WBjv8mNWDx6i

Output is per-occurrence, not per-category (see the plan,
C:\\Users\\ruben\\.claude\\plans\\tender-gliding-bunny.md): a category's "typical" time
is display metadata only, never what an actual entry anchors on.

Run once; output is checked in like lh5_pack.json/rf2_pack.json, not regenerated by
build_viewer3.py itself.
"""
import datetime
import json
import os
import re

import pandas as pd

import phase0_reconcile as P0
import rf2_tape

HERE = os.path.dirname(os.path.abspath(__file__))

# ---------------------------------------------------------------- manual verification
# The 31 DISAGREE rows, checked against official sources (see the report). Keyed by
# (date, ff_event) -> etMinute. 11 rows verified against a fixed official schedule
# (BLS 8:30/10:00, ADP 8:15, ISM/Conference Board/UMich 10:00); 13 FOMC-family rows
# resolved because both independent sources land within minutes of the same round
# historical FOMC time (12:30 or 14:15 ET pre-2019 depending on whether that meeting
# had a press conference, 14:00 ET from 2019 on); Not present here = still unresolved
# (7 speech rows -- no official fixed schedule to check a speech against, and the large
# gaps look like two different events under one label, not a timing error).
DISAGREE_VERIFIED = {
    ('2011-06-28', 'CB Consumer Confidence'): 10 * 60,
    ('2014-03-05', 'ISM Services PMI'): 10 * 60,
    ('2015-08-03', 'ISM Manufacturing PMI'): 10 * 60,
    ('2016-01-15', 'Prelim UoM Consumer Sentiment'): 10 * 60,
    ('2016-02-12', 'Prelim UoM Consumer Sentiment'): 10 * 60,
    ('2020-04-29', 'Advance GDP q/q'): 8 * 60 + 30,
    ('2021-03-10', 'CPI y/y'): 8 * 60 + 30,
    ('2021-05-14', 'Core Retail Sales m/m'): 8 * 60 + 30,
    ('2022-03-02', 'ADP Non-Farm Employment Change'): 8 * 60 + 15,
    ('2022-03-10', 'CPI y/y'): 8 * 60 + 30,
    ('2023-06-29', 'Unemployment Claims'): 8 * 60 + 30,
    # FOMC family: round time both sources land within minutes of
    ('2011-04-27', 'Federal Funds Rate'): 12 * 60 + 30,
    ('2011-06-22', 'Federal Funds Rate'): 12 * 60 + 30,
    ('2011-08-09', 'Federal Funds Rate'): 14 * 60 + 15,
    ('2011-09-21', 'FOMC Statement'): 14 * 60 + 15,
    ('2011-11-02', 'FOMC Statement'): 12 * 60 + 30,
    ('2011-11-22', 'FOMC Meeting Minutes'): 14 * 60,
    ('2011-12-13', 'FOMC Statement'): 14 * 60 + 15,
    ('2012-01-03', 'FOMC Meeting Minutes'): 14 * 60,
    ('2012-01-25', 'FOMC Statement'): 12 * 60 + 30,
    ('2012-06-20', 'FOMC Statement'): 12 * 60 + 30,
    ('2012-08-01', 'FOMC Statement'): 14 * 60 + 15,
    ('2015-08-19', 'FOMC Meeting Minutes'): 14 * 60,
    ('2020-01-03', 'FOMC Meeting Minutes'): 14 * 60,
}

# ---------------------------------------------------------------- OFFICIAL_STANDARD
# Never auto-shipped without an explicit per-category go-ahead (the plan's own rule).
# Approved 2026-09-21: categories with a genuinely fixed, single-time-of-day government
# or industry-published schedule, applied only to their DAY_ONLY occurrences (an
# occurrence that already has a real observed/cross-verified/verified time keeps it --
# this never overrides real data, only fills a gap neither source had anything for).
# Deliberately EXCLUDES the whole FOMC family (Federal Funds Rate, FOMC Statement,
# FOMC Meeting Minutes, FOMC Press Conference, FOMC Economic Projections) -- the
# historical DISAGREE resolution above proves the release time genuinely varies by
# era (12:30 / 14:00 / 14:15 ET), so a single blanket time would be actively wrong for
# some of the very occurrences it would apply to; those stay DAY_ONLY if unresolved.
OFFICIAL_STANDARD = {
    # BLS, confirmed 8:30 AM ET (bls.gov)
    'CPI y/y': (8 * 60 + 30, 'BLS standard schedule, bls.gov'),
    'CPI m/m': (8 * 60 + 30, 'BLS standard schedule, bls.gov'),
    'Core CPI m/m': (8 * 60 + 30, 'BLS standard schedule, bls.gov (same report as CPI)'),
    'PPI m/m': (8 * 60 + 30, 'BLS standard schedule, bls.gov'),
    'Core PPI m/m': (8 * 60 + 30, 'BLS standard schedule, bls.gov (same report as PPI)'),
    'Unemployment Rate': (8 * 60 + 30, 'BLS Employment Situation, bls.gov'),
    'Non-Farm Employment Change': (8 * 60 + 30, 'BLS Employment Situation, bls.gov'),
    'Average Hourly Earnings m/m': (8 * 60 + 30, 'BLS Employment Situation, bls.gov (same report)'),
    'JOLTS Job Openings': (10 * 60, 'BLS standard schedule, bls.gov'),
    # DOL, well-established weekly 8:30 AM ET
    'Unemployment Claims': (8 * 60 + 30, 'Dept. of Labor weekly release, well-established 8:30 ET'),
    # Census Bureau, well-established 8:30 AM ET
    'Retail Sales m/m': (8 * 60 + 30, 'Census Bureau standard schedule'),
    'Core Retail Sales m/m': (8 * 60 + 30, 'Census Bureau standard schedule (same report)'),
    # BEA, well-established 8:30 AM ET
    'Advance GDP q/q': (8 * 60 + 30, 'BEA standard schedule'),
    'Prelim GDP q/q': (8 * 60 + 30, 'BEA standard schedule (same report family)'),
    'Final GDP q/q': (8 * 60 + 30, 'BEA standard schedule (same report family)'),
    'Core PCE Price Index m/m': (8 * 60 + 30, 'BEA standard schedule'),
    # ADP, well-established 8:15 AM ET
    'ADP Non-Farm Employment Change': (8 * 60 + 15, 'ADP Research Institute standard schedule'),
    # ISM, well-established 10:00 AM ET
    'ISM Manufacturing PMI': (10 * 60, 'ISM standard schedule'),
    'ISM Services PMI': (10 * 60, 'ISM standard schedule'),
    # Conference Board, well-established 10:00 AM ET
    'CB Consumer Confidence': (10 * 60, 'Conference Board standard schedule'),
    # University of Michigan, well-established 10:00 AM ET
    'Prelim UoM Consumer Sentiment': (10 * 60, 'University of Michigan standard schedule'),
    'Revised UoM Consumer Sentiment': (10 * 60, 'University of Michigan standard schedule'),
    # NAR, confirmed 10:00 AM ET (nar.realtor)
    'Pending Home Sales m/m': (10 * 60, 'NAR standard schedule, nar.realtor'),
    # not a government schedule -- derived from this project's own data instead: all
    # 10 of Flash Services PMI's own CROSS_VERIFIED/SINGLE_SOURCE occurrences (2022,
    # 2023, 2025) land on exactly 09:45 ET with zero exceptions, stronger evidence
    # than an external source I couldn't reach
    'Flash Services PMI': (9 * 60 + 45, "this category's own 10/10 observed occurrences, unanimous"),
}

# ---------------------------------------------------------------- priority order
# For "Most important release": a fixed, documented, editable table -- not logic
# buried in the reduction function. Ties among checked, present categories break by
# this order only, deterministically, never by what price did afterward.
NEWS_PRIORITY = [
    'Federal Funds Rate', 'FOMC Statement',            # FOMC decision
    'Non-Farm Employment Change',                        # NFP
    'CPI m/m', 'CPI y/y', 'Core CPI m/m',
    'Core PCE Price Index m/m',
    'FOMC Press Conference', 'FOMC Meeting Minutes',
    'PPI m/m', 'Core PPI m/m',
    'Retail Sales m/m', 'Core Retail Sales m/m',
    'Advance GDP q/q', 'Prelim GDP q/q', 'Final GDP q/q',
    'ISM Manufacturing PMI', 'ISM Services PMI',
    'ADP Non-Farm Employment Change',
    'JOLTS Job Openings',
    'Unemployment Claims',
    'Unemployment Rate', 'Average Hourly Earnings m/m',
    'CB Consumer Confidence', 'Prelim UoM Consumer Sentiment', 'Revised UoM Consumer Sentiment',
    'Housing Starts', 'New Home Sales', 'Pending Home Sales m/m', 'Durable Goods Orders m/m',
    'Fed Chair Powell Speaks', 'Fed Chair Powell Testifies',
    'FOMC Member Bullard Speaks', 'FOMC Member Waller Speaks', 'FOMC Member Williams Speaks',
    'FOMC Economic Projections',
    # everything else: whatever order ALIAS enumerates them in
]


def slugify(name):
    return re.sub(r'_+', '_', re.sub(r'[^a-z0-9]+', '_', name.lower())).strip('_')


def et_minute(ts):
    if pd.isna(ts):
        return None
    return ts.hour * 60 + ts.minute


def main():
    print('Running Phase 0 reconciliation...')
    result = P0.main()
    rec = result['rec']

    priority_rank = {name: i for i, name in enumerate(NEWS_PRIORITY)}
    all_cats = sorted(P0.ALIAS.keys())
    for name in all_cats:
        if name not in priority_rank:
            priority_rank[name] = len(NEWS_PRIORITY) + all_cats.index(name)

    events = []
    for _, r in rec.iterrows():
        status = r.status
        override = DISAGREE_VERIFIED.get((r.date, r.ff_event))
        if status == 'DISAGREE' and override is not None:
            status = 'OFFICIAL_VERIFIED'
            et = override
        elif status == 'DISAGREE':
            et = None  # unresolved: 7 speech rows, stays non-tradable
        elif status in ('CROSS_VERIFIED', 'SINGLE_SOURCE_INVESTING'):
            et = et_minute(r.inv_et) if pd.notna(r.inv_et) else et_minute(r.ff_et)
        elif status == 'SINGLE_SOURCE_FF':
            et = et_minute(r.ff_et)
        else:  # INVESTING_INTERNAL_CONFLICT, UNMATCHED, AMBIGUOUS, DAY_ONLY
            et = None
        events.append({
            'date': r.date,
            'catId': slugify(r.ff_event),
            'eventName': r.ff_event,
            'etMinute': et,
            'status': status,
            'sourceTimes': {
                'ff': et_minute(r.ff_et) if pd.notna(r.ff_et) else None,
                'investing': et_minute(r.inv_et) if pd.notna(r.inv_et) else None,
            },
        })

    # ---------------- FOMC decision day supplement (rf2_tape.fomc_days(), 2016-2026) ----------------
    # Fills gaps in Forex Factory's own Federal Funds Rate/FOMC Statement coverage (2012-2013,
    # parts of 2020-2021) and extends past its 2025-04-04 end. Where a decision date already has
    # a resolved time from the reconciled Federal Funds Rate/FOMC Statement events, reuse it
    # (linked, not re-derived); a gap date with no such resolution stays DAY_ONLY -- OFFICIAL_STANDARD
    # (e.g. asserting 14:00 ET) is never auto-shipped per the plan, only on your explicit go-ahead.
    events_df_tmp = pd.DataFrame(events)
    fomc_resolved = events_df_tmp[
        events_df_tmp.eventName.isin(['Federal Funds Rate', 'FOMC Statement'])
        & events_df_tmp.etMinute.notna()
    ].groupby('date').etMinute.first().to_dict()
    fomc_status = events_df_tmp[
        events_df_tmp.eventName.isin(['Federal Funds Rate', 'FOMC Statement'])
    ].groupby('date').status.first().to_dict()
    FOMC_CAT_ID, FOMC_CAT_NAME = 'fomc_decision_day', 'FOMC decision day'
    for d in sorted(rf2_tape.fomc_days()):
        et = fomc_resolved.get(d)
        status = fomc_status.get(d, 'DAY_ONLY') if et is not None else 'DAY_ONLY'
        events.append({
            'date': d, 'catId': FOMC_CAT_ID, 'eventName': FOMC_CAT_NAME,
            'etMinute': et, 'status': status,
            'sourceTimes': {'ff': None, 'investing': None},
        })
    all_cats.append(FOMC_CAT_NAME)
    priority_rank[FOMC_CAT_NAME] = -1  # highest priority: the decision itself

    # categories: name, note (coverage-gap caveats from the FF README), priority rank,
    # display-only typical time (mode of resolved etMinute values -- never an anchor)
    NOTES = {
        'Unemployment Claims': 'Forex Factory\u2019s own source documents this as unreliable for '
            'systematic use \u2014 whole years missing (2007, 2019, 2021, 2022), roughly 33/yr '
            'observed vs. the true weekly ~52.',
        'Durable Goods Orders m/m': 'The underlying Forex Factory source is missing this '
            'category\u2019s data entirely 2021\u20132025.',
        'CB Consumer Confidence': 'Sparse 2020\u20132022 (COVID-era scraper gaps) in the underlying source.',
    }
    events_df = pd.DataFrame(events)
    categories = []
    for name in all_cats:
        cid = slugify(name)
        cat_ev = events_df[events_df.catId == cid]
        resolved = cat_ev[cat_ev.etMinute.notna()]
        typical = int(resolved.etMinute.mode().iloc[0]) if len(resolved) else None
        categories.append({
            'id': cid, 'name': name, 'note': NOTES.get(name),
            'priorityRank': priority_rank[name],
            'typicalEtMinute': typical,
        })

    ff_min, ff_max = result['ff_coverage']
    inv_min, inv_max = result['investing_coverage']
    cross_min = max(ff_min, inv_min)
    cross_max = min(ff_max, inv_max)

    out = {
        'builtFrom': 'phase0_reconcile.py + manual verification, ' + datetime.date.today().isoformat(),
        'ffCoverage': [ff_min, ff_max],
        'investingCoverage': [inv_min, inv_max],
        'crossVerifiedCoverage': [cross_min, cross_max],
        'newsPriority': NEWS_PRIORITY,
        'categories': categories,
        'events': events,
    }
    out_path = os.path.join(HERE, 'news_calendar.json')
    with open(out_path, 'w') as f:
        json.dump(out, f, separators=(',', ':'))
    print('\nWrote', out_path, '--', len(events), 'events,', len(categories), 'categories')
    print('status counts in final events:')
    print(events_df.status.value_counts())
    resolvable = events_df[events_df.etMinute.notna()]
    print('events with a usable etMinute (timing-preset eligible):', len(resolvable))


if __name__ == '__main__':
    main()
